CREATE EXTENSION "uuid-ossp";

CREATE SCHEMA IF NOT EXISTS ARCHIVE;

CREATE TABLE IF NOT EXISTS ARCHIVE.GAME (
  GAME_ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  REMOTE_ID TEXT,
  SHOW_ID TEXT,
  TYPE TEXT,
  COMMENT TEXT,
  AIR_DATE DATE
);

CREATE TABLE IF NOT EXISTS ARCHIVE.CATEGORY (
  CATEGORY_ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  NAME TEXT NOT NULL,
  HINT TEXT,
  AIR_DATE DATE,
  ROUND SMALLINT,
  GAME_ID UUID REFERENCES ARCHIVE.GAME (GAME_ID)
);

CREATE TABLE IF NOT EXISTS ARCHIVE.CLUE (
  CLUE_ID      UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  QUESTION     TEXT NOT NULL,
  VALUE        SMALLINT,
  DAILY_DOUBLE BOOLEAN,
  MEDIA        TEXT[],
  ANSWER       TEXT[],
  CATEGORY_ID  UUID REFERENCES ARCHIVE.CATEGORY (CATEGORY_ID)
);

CREATE SCHEMA PLAY;

CREATE TABLE IF NOT EXISTS PLAY.SERVER (
  SERVER_ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  PROVIDER TEXT NOT NULL,
  REMOTE_ID TEXT NOT NULL,
  NAME TEXT,
  ACTIVE BOOLEAN DEFAULT TRUE,
  CREATED_AT TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS PLAY.CHANNEL (
  CHANNEL_ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  SERVER_ID UUID REFERENCES PLAY.SERVER (SERVER_ID),
  REMOTE_ID TEXT NOT NULL,
  ACTIVE BOOLEAN DEFAULT TRUE,
  CREATED_AT TIMESTAMP DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS PLAY.PLAYER (
  PLAYER_ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  SERVER_ID UUID REFERENCES PLAY.SERVER (SERVER_ID),
  REMOTE_ID TEXT NOT NULL,
  DISPLAY_NAME TEXT
);

CREATE TABLE IF NOT EXISTS PLAY.GAME (
  GAME_ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  CHANNEL_ID UUID REFERENCES PLAY.CHANNEL (CHANNEL_ID),
  CATEGORIES UUID[],
  CREATED_AT TIMESTAMP DEFAULT NOW(),
  ENDED_AT TIMESTAMP
);

CREATE TABLE IF NOT EXISTS PLAY.PLAYER_GAME_SCORE (
  GAME_ID UUID REFERENCES PLAY.GAME (GAME_ID),
  PLAYER_ID UUID REFERENCES PLAY.PLAYER (PLAYER_ID),
  SCORE SMALLINT,
  CLUES_CORRECT SMALLINT,
  CLUES_INCORRECT SMALLINT,
  PRIMARY KEY (GAME_ID, PLAYER_ID)
);
